# Day 7 of python3

## Today I learned ...

- 꿀팁1: for문이나 if문, try/except 구문을 작성할 땐 일단 pass를 써두고 작성하여 나중에 코드가 누락되었을 때 귀찮아지는 일이 없도록 하자
- 꿀팁2: 2개의 리스트에 대해 for문을 돌려야 하는 경우, `zip`함수를 이용하면 두 개의 리스트를 합쳐준다. 필요할 때마다 필요한 만큼 하나씩만 짝을 지어 그걸 for문에 넣어주면서 리소스를 효율적으로 사용할 수 있다.
```
numbers = [i for i in range(10)]
chars = [a,b,c,d,e,f,g,h,i,j]
zip(numbers, chars)
coords = zip(numbers, chars)
next(coords) #작동시킬때마다 한쌍이 튀어나온다.
for i, c in zip(numbers, chars):
  print(i,c) 
#리스트 2개에 동시에 for문을 돌려야 하면 zip함수를 쓰자.
```

1. Error Handling (Try Except)
- 에러가 발생하는 경우 에러메시지를 띄우는 대신 할 작업을 정해준다.
```
try:
  result = 3/0 
except:
  print('You cannot divide by zero')
```
- 사용자의 인풋이나 DB 등 외부와 주고받는 과정에서 우리가 통제할 수 없는 변인에 대해서 활용할 수 있다. ex. numguess게임에서 사용자가 input을 string으로 입력하는 경우
```
try:
  guess = int(input('Guess the number: '))
except:
  print("Don't bother programmer")
  guess = int(input('Guess the number: '))
#다시 string을 입력하면 에러가 난다.
```
- 동일한 에러에 대해서 try 행동을 다시 유도하려면 재귀함수를 사용한다.
```
def get_num():
  try:
    guess = int(input('Guess the number: ')
    return guess
  except ValueError: #except 뒤에 에러타입을 적어주면 해당 에러에 대해서만 작업 수행
    print("Don't bother programmer")
    return get_num()

get_num()
```
- `except {에러이름}` 구문은 여러번 같은 indentation으로 써서 각 error에 대한 대응을 달리 할 수 있다. (NameError, FileNotFoundError 등)
- 지정된 error 외의 모든 에러에 대해서는 `else:` 구문으로 처리한다. 

2. RegEx (Regular Expression)

